name: Docker CD

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nestoragc123/docker-angular-app-web
        tags: latest
        tag_with_sha: true
        path: ./web
        dockerfile: ./web/prod.Dockerfile

